# Generated by Django 2.1.4 on 2018-12-16 19:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('name', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Ticker name')),
            ],
        ),
        migrations.CreateModel(
            name='TickerPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=11, verbose_name='Open')),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=11, verbose_name='High')),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=11, verbose_name='Low')),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=11, verbose_name='Close')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stock.Ticker', verbose_name='Ticker')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=64, verbose_name='Relation')),
                ('last_date', models.DateField(default=django.utils.timezone.now, verbose_name='Last Date')),
                ('transaction_type', models.CharField(max_length=128, verbose_name='Transaction Type')),
                ('owner_type', models.CharField(max_length=32, verbose_name='OwnerType')),
                ('shares_traded', models.PositiveIntegerField(verbose_name='Shares Traded')),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='Last Price')),
                ('shares_held', models.PositiveIntegerField(default=0, verbose_name='Shares Held')),
                ('insider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stock.Insider', verbose_name='Insider')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stock.Ticker', verbose_name='Ticker')),
            ],
        ),
    ]
